import { useEffect, useState } from 'react';
import ClayCard from '../components/ClayCard.jsx';
import Table from '../components/Table.jsx';
import Modal from '../components/Modal.jsx';
import { api } from '../services/api.js';

function useLoad(path) { const [data, setData] = useState([]); const [error, setError] = useState(''); useEffect(() => { api(path).then(setData).catch((e) => setError(e.message)); }, [path]); return { data, setData, error }; }

export function MembersPage() {
  const { data, setData, error } = useLoad('/members'); const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: '', email: '', password: 'Member 123', phone: '', goal: '', plan: 'Starter · 1 Month', amount: 1500 });
  async function create(e) { e.preventDefault(); try { const created = await api('/members', { method: 'POST', body: JSON.stringify({ ...form, amount: Number(form.amount) }) }); setData((items) => [{ ...created }, ...items]); setOpen(false); setForm({ name: '', email: '', password: 'Member 123', phone: '', goal: '', plan: 'Starter · 1 Month', amount: 1500 }); } catch (err) { alert(err.message); } }
  return <><PageHead eyebrow="MEMBERS" title="Member directory" action={<button className="primary-button small" onClick={() => setOpen(true)}>+ Add member</button>}/><ClayCard>{error ? <div className="error-banner">{error}</div> : <Table columns={['Member', 'Email', 'Goal', 'Plan', 'Status']} rows={data.map((m) => ({ key: m.id, cells: [<strong>{m.name}</strong>, m.email, m.goal || '—', m.membership?.plan || 'No plan', <span className={`status-pill ${m.membership?.status === 'ACTIVE' ? 'success' : 'neutral'}`}>{m.membership?.status || 'UNASSIGNED'}</span>] }))}/>}</ClayCard>{open && <Modal title="Add member" onClose={() => setOpen(false)}><form className="form-grid" onSubmit={create}><Field label="Full name" value={form.name} onChange={(v) => setForm({ ...form, name: v })}/><Field label="Email" value={form.email} onChange={(v) => setForm({ ...form, email: v })} type="email"/><Field label="Phone" value={form.phone} onChange={(v) => setForm({ ...form, phone: v })}/><Field label="Goal" value={form.goal} onChange={(v) => setForm({ ...form, goal: v })}/><Field label="Plan" value={form.plan} onChange={(v) => setForm({ ...form, plan: v })}/><Field label="Amount" value={form.amount} onChange={(v) => setForm({ ...form, amount: v })} type="number"/><Field label="Initial password" value={form.password} onChange={(v) => setForm({ ...form, password: v })} type="password"/><button className="primary-button full-span">Create member</button></form></Modal>}</>;
}

export function MembershipsPage() { const { data, error } = useLoad('/admin/memberships'); return <><PageHead eyebrow="MEMBERSHIPS" title="Plans & renewals"/><ClayCard>{error ? <div className="error-banner">{error}</div> : <Table columns={['Member', 'Plan', 'Amount', 'Status', 'Start', 'End']} rows={data.map((x) => ({ key: x.id, cells: [x.member, x.plan, x.amount ? `₹${x.amount}` : '—', <span className="status-pill success">{x.status}</span>, new Date(x.startDate).toLocaleDateString(), new Date(x.endDate).toLocaleDateString()] }))}/>}</ClayCard></>; }
export function TrainersPage() { const { data, setData, error } = useLoad('/admin/trainers'); const [name, setName] = useState(''); const [speciality, setSpeciality] = useState(''); async function add() { try { const row = await api('/admin/trainers', { method: 'POST', body: JSON.stringify({ name, speciality }) }); setData((rows) => [...rows, row]); setName(''); setSpeciality(''); } catch (e) { alert(e.message); } } return <><PageHead eyebrow="TRAINERS" title="Trainer directory"/><ClayCard><div className="inline-form"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Trainer name"/><input value={speciality} onChange={(e) => setSpeciality(e.target.value)} placeholder="Speciality"/><button className="primary-button small" onClick={add}>Add trainer</button></div>{error && <div className="error-banner">{error}</div>}<Table columns={['Name', 'Speciality', 'Phone']} rows={data.map((x) => ({ key: x.id, cells: [x.name, x.speciality || '—', x.phone || '—'] }))}/></ClayCard></>; }
export function AttendancePage() { const { data, error } = useLoad('/admin/attendance'); return <><PageHead eyebrow="ATTENDANCE" title="Check-in history"/><ClayCard>{error ? <div className="error-banner">{error}</div> : <Table columns={['Member', 'Date', 'Status']} rows={data.map((x) => ({ key: x.id, cells: [x.member, new Date(x.date).toLocaleString(), <span className="status-pill success">{x.status}</span>] }))}/>}</ClayCard></>; }
export function WorkoutsPage() { const { data, error } = useLoad('/admin/workouts'); return <><PageHead eyebrow="WORKOUTS" title="Workout records"/><ClayCard>{error ? <div className="error-banner">{error}</div> : <Table columns={['Workout', 'Member', 'Trainer', 'Duration', 'Date']} rows={data.map((x) => ({ key: x.id, cells: [<strong>{x.title || 'Workout'}</strong>, x.member, x.trainer, x.duration ? `${x.duration} min` : '—', new Date(x.date).toLocaleDateString()] }))}/>}</ClayCard></>; }
export function EquipmentPage() { const { data, setData, error } = useLoad('/admin/equipment'); async function update(id, status) { try { const updated = await api(`/admin/equipment/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); setData((rows) => rows.map((row) => row.id === id ? updated : row)); } catch (e) { alert(e.message); } } return <><PageHead eyebrow="EQUIPMENT" title="Asset control"/><div className="equipment-grid">{data.map((item) => <ClayCard key={item.id} className="equipment-card"><span className="category">{item.category}</span><h3>{item.name}</h3><div className="equipment-actions"><span className={`status-pill ${item.status === 'AVAILABLE' ? 'success' : item.status === 'MAINTENANCE' ? 'warning' : 'neutral'}`}>{item.status}</span><select value={item.status} onChange={(e) => update(item.id, e.target.value)}><option>AVAILABLE</option><option>MAINTENANCE</option><option>RETIRED</option></select></div></ClayCard>)}</div>{error && <div className="error-banner">{error}</div>}</>; }
export function PaymentsPage() { return <><PageHead eyebrow="PAYMENTS" title="Payment gateway"/><ClayCard className="upcoming-card"><span className="eyebrow">UPCOMING</span><h2>Online payments are in the next phase.</h2><p>The PostgreSQL payment records are already modeled and visible. Gateway checkout, webhook verification and receipt automation will be added after the current review.</p><div className="upcoming-steps"><span>1 · Gateway integration</span><span>2 · Webhook verification</span><span>3 · Receipt automation</span></div></ClayCard></>; }

function PageHead({ eyebrow, title, action }) { return <div className="page-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{action}</div>; }
function Field({ label, value, onChange, type = 'text' }) { return <label>{label}<input type={type} value={value} onChange={(e) => onChange(e.target.value)} required/></label>; }
