import ClayCard from '../components/ClayCard.jsx';

export default function OverviewPage({ role, data, user, setPage }) {
  if (role === 'ADMIN') {
    const m = data?.metrics || {};
    return <><section className="welcome-row"><div><span className="eyebrow">ADMIN WORKSPACE</span><h2>Good to see you, {user.name.split(' ')[0]}.</h2><p>Live club operations backed by PostgreSQL on Neon.</p></div><span className="database-badge">PostgreSQL · Neon</span></section><section className="stat-grid">{[['Members', m.members ?? 0, 'Registered member profiles'], ['Active plans', m.activeMemberships ?? 0, 'Memberships currently active'], ['Today', m.todayAttendance ?? 0, 'Present check-ins'], ['Attention', (m.pendingPayments ?? 0) + (m.equipmentMaintenance ?? 0), 'Payments + equipment']].map(([title, value, text]) => <ClayCard key={title} className="stat-card"><span>{title}</span><strong>{value}</strong><small>{text}</small></ClayCard>)}</section><section className="content-grid"><ClayCard><div className="section-head"><div><span className="eyebrow">QUICK ACTIONS</span><h3>Club management</h3></div></div><div className="quick-grid">{['Members', 'Memberships', 'Trainers', 'Attendance', 'Workouts', 'Equipment'].map((item) => <button key={item} onClick={() => setPage(item)} className="quick-card"><span>{item.slice(0, 2).toUpperCase()}</span><strong>{item}</strong><small>Open module →</small></button>)}</div></ClayCard><ClayCard><div className="section-head"><div><span className="eyebrow">REVIEW 3</span><h3>Database evidence</h3></div></div><div className="evidence"><div><b>1</b><span>React UI → Express API</span></div><div><b>2</b><span>JWT role protection</span></div><div><b>3</b><span>Prisma → Neon PostgreSQL</span></div><div><b>4</b><span>Real records, no mock rows</span></div></div></ClayCard></section></>;
  }
  const m = data?.metrics || {};
  return <><section className="member-hero clay-card"><div><span className="eyebrow">MEMBER PORTAL</span><h2>Your fitness space, {user.name.split(' ')[0]}.</h2><p>See your active plan, attendance, workouts and payment records in one place.</p></div><div className="member-plan"><span>Current plan</span><strong>{data?.membership?.plan || 'No active plan'}</strong><small>{data?.membership?.endDate ? `Ends ${new Date(data.membership.endDate).toLocaleDateString()}` : 'Contact admin to activate a plan'}</small></div></section><section className="stat-grid three">{[['Attendance', m.attendance ?? 0, 'Present check-ins'], ['Workouts', m.workouts ?? 0, 'Workout records'], ['Payments', m.payments ?? 0, 'Payment records']].map(([title, value, text]) => <ClayCard key={title} className="stat-card"><span>{title}</span><strong>{value}</strong><small>{text}</small></ClayCard>)}</section></>;
}
